exports.roles = {
    student: [
        "CODING_CHALLENGE_GET",
        "CODING_CHALLENGE_UPDATE_PROGRESS",
        "FORUM_THREAD_GET",
        "FORUM_THREAD_POST",
        "FORUM_THREAD_LIKE",
        "FORUM_THREAD_PUT",
        "FORUM_THREAD_DELETE",
        "GOAL_GET",
        "LEADERBOARD_GET",
        "LINKEDIN_GET",
        "POST_GET",
        "POST_CREATE",
        "POST_EDIT",
        "POST_DELETE",
        "POST_LIKE",
        "REWARD_GET",
        "REWARD_POST",
        "ROADMAP_GET",
        "ROADMAP_POST",
        "USER_GET",
        "USER_POST",
        "USER_PUT",
    ],
    moderator: ["MODERATOR_DASHBOARD_GET"],
    alumni: [""],
    admin: [
        "CODING_CHALLENGE_GET",
        "CODING_CHALLENGE_UPDATE_PROGRESS",
        "CODING_CHALLENGE_POST",
        "CODING_CHALLENGE_DELETE",
        "MODERATOR_DASHBOARD_GET",
        "FORUM_THREAD_GET",
        "FORUM_THREAD_POST",
        "FORUM_THREAD_LIKE",
        "FORUM_THREAD_PUT",
        "FORUM_THREAD_DELETE",
        "GOAL_GET",
        "LEADERBOARD_GET",
        "LINKEDIN_GET",
        "POST_GET",
        "POST_CREATE",
        "POST_EDIT",
        "POST_DELETE",
        "POST_LIKE",
        "REWARD_GET",
        "REWARD_POST",
        "ROADMAP_GET",
        "ROADMAP_POST",
        "ROADMAP_PUT",
        "ROADMAP_DELETE",
        "USER_GET",
        "USER_POST",
        "USER_PUT",
        "USER_DELETE",
    ],
};
